#!/bin/bash

ABSPATH=$(cd "$(dirname "$0")"; pwd)

echo ""
echo ""
echo "-=== ALL PARAMS ===-"
echo $@
echo ""
echo ""
echo "-=== FILTERED PARAMS ===-"
FILTEREDPARAMS=`$ABSPATH/filterargs $@`
FNAME=`$ABSPATH/filtername $@`


echo $FILTEREDPARAMS

echo ""
echo ""
/usr/bin/gcc $@


# run typechef only in case we have a c file
if [[ -n $FNAME ]];
then
	# set output files
	outBase="$(dirname $FNAME)/$(basename $FNAME .c)"
	outDbg="$outBase.dbg"
	outPartialPreproc="$outBase.pi"
	outErr="$outBase.err"
	outTime="$outBase.time"

	# TypeChef resides next to TypeChef-<projectname> two levels up
	$ABSPATH/../../TypeChef/typechef.sh \
		--bdd \
		-I /usr/local/include \
		-I /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed \
		-I /usr/lib/gcc/x86_64-linux-gnu/4.6/include \
		-I /usr/include/x86_64-linux-gnu \
		-I /usr/include \
		--platfromHeader    $ABSPATH/platform.h \
		--openFeat          $ABSPATH/openfeatures.txt \
		--featureModelFExpr $ABSPATH/fm.txt \
		--typeSystemFeatureModelDimacs $ABSPATH/openssl.dimacs \
		--writePI $FILTEREDPARAMS \
		--typecheck \
		--include $ABSPATH/partial_configuration.h \
		$FNAME \
		2> "$outErr" | tee "$outDbg"

	cat $outErr
fi

echo ""
echo ""
