#ifdef DTLS1_AD_MISSING_HANDSHAKE_MESSAGE
    #define DTLS1_AD_MISSING_HANDSHAKE_MESSAGE "anystring"
#endif

#ifdef NO_WINDOWS_BRAINDEATH
    #define NO_WINDOWS_BRAINDEATH "anystring"
#endif

#ifdef OPENSSLDIR
    #define OPENSSLDIR "anystring"
#endif

#ifdef OPENSSL_NO_TLSEXT
    #define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME 0
    #define SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD 0
    #define SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH 0
    #define SSL_CTRL_SET_SRP_VERIFY_PARAM_CB 0
    #define SSL_CTRL_SET_SRP_ARG 0
    #define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB 0
    #define SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB 0
#endif

#define _BITS_STDIO_LOCK_H

#undef OPENSSL_NO_HEARTBEATS
#undef OPENSSL_NO_BIO
#undef OPENSSL_NO_FP_API
#undef OPENSSL_NO_STDIO
#undef OPENSSL_NO_COMP
#undef _LIBC
#undef WSAAPI
#undef EVP_CHECK_DES_KEY
#undef KSSL_DEBUG
#undef TLS_DEBUG
